# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: kinovagen3_arm
  joint_model_group_pose: upright
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - base_shoulder1
    - shoulder1_halfarm1
    - halfarm1_halfarm2
    - halfarm2_forearm1
    - forearm1_sphericalwrist1
    - sphericalwrist1_sphericalwirst2
    - sphericalwrist2_eecoupler
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:  
  - name: ""
    action_ns: kinovagen3_unity_actionserver
    type: FollowJointTrajectory
    allowed_execution_duration_scaling: 10.0
    allowed_goal_duration_margin: 10.0
    default: true
    joints:
      - base_shoulder1
      - shoulder1_halfarm1
      - halfarm1_halfarm2
      - halfarm2_forearm1
      - forearm1_sphericalwrist1
      - sphericalwrist1_sphericalwirst2    
      - sphericalwrist2_eecoupler    
arm_position_controller:
  type: position_controllers/JointPositionController
  joints:
    - base_shoulder1
    - shoulder1_halfarm1
    - halfarm1_halfarm2
    - halfarm2_forearm1
    - forearm1_sphericalwrist1
    - sphericalwrist1_sphericalwirst2
    - sphericalwrist2_eecoupler
  gains:
    base_shoulder1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    shoulder1_halfarm1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    halfarm1_halfarm2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    halfarm2_forearm1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    forearm1_sphericalwrist1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    sphericalwrist1_sphericalwirst2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    sphericalwrist2_eecoupler:
      p: 100
      d: 1
      i: 1
      i_clamp: 1